### ISSUE TITLE
INVALID TOKEN

### ISSUE THREAD

**Issue by sh0e** [OBNinjaa/discord-selfbot#1]
(node:517) UnhandledPromiseRejectionWarning: Error [TOKEN_INVALID]: An invalid token was provided.

**Comment by OBNinjaa** [comment]
You can only use discord.js version 11. So in package.json edit the version number to 11.6.1
 then delete node_modules and then do npm i again.

![js](https://user-images.githubusercontent.com/64389208/105660843-db8cbf00-5ec3-11eb-81d7-daf4f3f57535.PNG)

**Comment by sh0e** [comment]
oh let me try, thanks!
